const { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell, ImageRun,
        Header, Footer, AlignmentType, LevelFormat,
        HeadingLevel, BorderStyle, WidthType,
        ShadingType, VerticalAlign, PageNumber, PageBreak,
        HorizontalPositionRelativeFrom, VerticalPositionRelativeFrom,
        HorizontalPositionAlign, VerticalPositionAlign } = require('docx');
const fs = require('fs');
const path = require('path');

// Brand Colors
const BLUE = "1E5FAA";
const DARK_BLUE = "0A2744";
const ACCENT_BLUE = "2B7DE9";
const GRAY = "4A4A4A";
const LIGHT_GRAY = "F0F4F8";
const LIGHT_BLUE = "E3F2FD";
const WHITE = "FFFFFF";

const noBorder = { style: BorderStyle.NONE, size: 0, color: WHITE };
const noBorders = { top: noBorder, bottom: noBorder, left: noBorder, right: noBorder };

// Helper for bold stat boxes with colored backgrounds
function createStatBox(number, label, bgColor) {
  return new Table({
    columnWidths: [2800],
    rows: [
      new TableRow({
        children: [
          new TableCell({
            borders: noBorders,
            shading: { fill: bgColor, type: ShadingType.CLEAR },
            width: { size: 2800, type: WidthType.DXA },
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                spacing: { before: 200, after: 0 },
                children: [new TextRun({ text: number, bold: true, size: 72, color: WHITE, font: "Arial" })]
              }),
              new Paragraph({
                alignment: AlignmentType.CENTER,
                spacing: { before: 0, after: 200 },
                children: [new TextRun({ text: label, size: 20, color: WHITE, font: "Arial" })]
              })
            ]
          })
        ]
      })
    ]
  });
}

// Bold pull quote with thick accent bar
function createPullQuote(text, attribution) {
  return new Table({
    columnWidths: [360, 9000],
    rows: [
      new TableRow({
        children: [
          new TableCell({
            borders: noBorders,
            shading: { fill: ACCENT_BLUE, type: ShadingType.CLEAR },
            width: { size: 360, type: WidthType.DXA },
            children: [new Paragraph({ children: [] })]
          }),
          new TableCell({
            borders: noBorders,
            shading: { fill: LIGHT_BLUE, type: ShadingType.CLEAR },
            width: { size: 9000, type: WidthType.DXA },
            children: [
              new Paragraph({
                spacing: { before: 200, after: 100 },
                indent: { left: 200 },
                children: [new TextRun({ text: `"${text}"`, italics: true, size: 26, color: DARK_BLUE, font: "Arial" })]
              }),
              new Paragraph({
                spacing: { before: 0, after: 200 },
                indent: { left: 200 },
                children: [new TextRun({ text: `— ${attribution}`, bold: true, size: 20, color: GRAY, font: "Arial" })]
              })
            ]
          })
        ]
      })
    ]
  });
}

// Section header with colored background
function createSectionHeader(text) {
  return new Table({
    columnWidths: [9360],
    rows: [
      new TableRow({
        children: [
          new TableCell({
            borders: noBorders,
            shading: { fill: DARK_BLUE, type: ShadingType.CLEAR },
            width: { size: 9360, type: WidthType.DXA },
            children: [
              new Paragraph({
                spacing: { before: 200, after: 200 },
                children: [new TextRun({ text: text.toUpperCase(), bold: true, size: 36, color: WHITE, font: "Arial" })]
              })
            ]
          })
        ]
      })
    ]
  });
}

// Read cover image (generated by Nano Banana)
const scriptDir = path.dirname(__filename);
const rootDir = path.join(scriptDir, '..');
const coverImagePath = path.join(rootDir, 'output', 'cover_image.png');
const coverImageData = fs.readFileSync(coverImagePath);

const doc = new Document({
  styles: {
    default: { document: { run: { font: "Arial", size: 24 } } },
    paragraphStyles: [
      { id: "Title", name: "Title", basedOn: "Normal",
        run: { size: 72, bold: true, color: WHITE, font: "Arial" },
        paragraph: { spacing: { before: 0, after: 120 }, alignment: AlignmentType.CENTER } },
      { id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 44, bold: true, color: DARK_BLUE, font: "Arial" },
        paragraph: { spacing: { before: 400, after: 200 }, outlineLevel: 0 } },
      { id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 32, bold: true, color: ACCENT_BLUE, font: "Arial" },
        paragraph: { spacing: { before: 300, after: 150 }, outlineLevel: 1 } },
      { id: "Heading3", name: "Heading 3", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 26, bold: true, color: GRAY, font: "Arial" },
        paragraph: { spacing: { before: 200, after: 100 }, outlineLevel: 2 } },
    ]
  },
  numbering: {
    config: [
      { reference: "bullet-list",
        levels: [{ level: 0, format: LevelFormat.BULLET, text: "•", alignment: AlignmentType.LEFT,
          style: { paragraph: { indent: { left: 720, hanging: 360 } } } }] },
      { reference: "numbered-list-1",
        levels: [{ level: 0, format: LevelFormat.DECIMAL, text: "%1.", alignment: AlignmentType.LEFT,
          style: { paragraph: { indent: { left: 720, hanging: 360 } } } }] },
      { reference: "numbered-list-2",
        levels: [{ level: 0, format: LevelFormat.DECIMAL, text: "%1.", alignment: AlignmentType.LEFT,
          style: { paragraph: { indent: { left: 720, hanging: 360 } } } }] }
    ]
  },
  sections: [
    // ============ McKINSEY-STYLE COVER PAGE ============
    {
      properties: {
        page: { margin: { top: 0, right: 0, bottom: 0, left: 0 } }
      },
      children: [
        // Full-bleed background image - oversized for guaranteed coverage
        new Paragraph({
          children: [
            new ImageRun({
              type: "png",
              data: coverImageData,
              transformation: { width: 650, height: 842 }, // Oversized for full bleed
              floating: {
                horizontalPosition: {
                  relative: HorizontalPositionRelativeFrom.PAGE,
                  align: HorizontalPositionAlign.CENTER,
                },
                verticalPosition: {
                  relative: VerticalPositionRelativeFrom.PAGE,
                  align: VerticalPositionAlign.CENTER,
                },
                behindDocument: true,
              },
              altText: { title: "Cover Image", description: "AI-generated abstract cover", name: "cover" }
            })
          ]
        }),
        // Company name at top left
        new Paragraph({
          spacing: { before: 400, after: 0 },
          indent: { left: 400 },
          children: [
            new TextRun({ text: "Prompt Advisers", bold: true, size: 28, color: WHITE, font: "Arial" })
          ]
        }),
        // Spacer to push title down
        new Paragraph({ spacing: { before: 4000 }, children: [] }),
        new Paragraph({ spacing: { before: 2000 }, children: [] }),
        // Semi-transparent backdrop for title area
        new Table({
          columnWidths: [12240],
          rows: [
            new TableRow({
              height: { value: 4800, rule: "atLeast" },
              children: [
                new TableCell({
                  borders: noBorders,
                  shading: { fill: "1A3A5C", type: ShadingType.CLEAR }, // Dark blue-gray backdrop
                  width: { size: 12240, type: WidthType.DXA },
                  verticalAlign: VerticalAlign.CENTER,
                  children: [
                    // Main title - THE STATE
                    new Paragraph({
                      alignment: AlignmentType.LEFT,
                      indent: { left: 400 },
                      spacing: { before: 200, after: 0 },
                      children: [
                        new TextRun({ text: "THE STATE", bold: true, size: 96, color: WHITE, font: "Arial" })
                      ]
                    }),
                    // OF AI
                    new Paragraph({
                      alignment: AlignmentType.LEFT,
                      indent: { left: 400 },
                      spacing: { before: 0, after: 0 },
                      children: [
                        new TextRun({ text: "OF ", bold: true, size: 96, color: WHITE, font: "Arial" }),
                        new TextRun({ text: "AI", bold: true, size: 96, color: "5BB5E0", font: "Arial" })
                      ]
                    }),
                    // Year
                    new Paragraph({
                      alignment: AlignmentType.LEFT,
                      indent: { left: 400 },
                      spacing: { before: 100, after: 200 },
                      children: [
                        new TextRun({ text: "2026", bold: true, size: 96, color: WHITE, font: "Arial" })
                      ]
                    }),
                    // Subtitle
                    new Paragraph({
                      alignment: AlignmentType.LEFT,
                      indent: { left: 400 },
                      spacing: { before: 200, after: 0 },
                      children: [
                        new TextRun({ text: "Enterprise Adoption, Implementation Strategies", size: 28, color: WHITE, font: "Arial" }),
                      ]
                    }),
                    new Paragraph({
                      alignment: AlignmentType.LEFT,
                      indent: { left: 400 },
                      spacing: { before: 0, after: 200 },
                      children: [
                        new TextRun({ text: "& Technologies Reshaping Business", size: 28, color: WHITE, font: "Arial" }),
                      ]
                    })
                  ]
                })
              ]
            })
          ]
        }),
        // Spacer before bottom bar
        new Paragraph({ spacing: { before: 1600 }, children: [] }),
        // Bottom accent bar with category
        new Table({
          columnWidths: [12240],
          rows: [
            new TableRow({
              height: { value: 600, rule: "exact" },
              children: [
                new TableCell({
                  borders: noBorders,
                  shading: { fill: DARK_BLUE, type: ShadingType.CLEAR },
                  width: { size: 12240, type: WidthType.DXA },
                  verticalAlign: VerticalAlign.CENTER,
                  children: [
                    new Paragraph({
                      indent: { left: 400 },
                      children: [
                        new TextRun({ text: "Prompt Advisers on AI Strategy", size: 22, color: WHITE, font: "Arial" })
                      ]
                    })
                  ]
                })
              ]
            })
          ]
        })
      ]
    },
    // ============ TABLE OF CONTENTS PAGE ============
    {
      properties: {
        page: { margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } }
      },
      children: [
        // TOC Header
        new Table({
          columnWidths: [9360],
          rows: [
            new TableRow({
              children: [
                new TableCell({
                  borders: { top: noBorder, bottom: { style: BorderStyle.SINGLE, size: 18, color: ACCENT_BLUE }, left: noBorder, right: noBorder },
                  width: { size: 9360, type: WidthType.DXA },
                  children: [
                    new Paragraph({
                      spacing: { before: 0, after: 200 },
                      children: [new TextRun({ text: "CONTENTS", bold: true, size: 52, color: DARK_BLUE, font: "Arial" })]
                    })
                  ]
                })
              ]
            })
          ]
        }),
        new Paragraph({ spacing: { before: 400 }, children: [] }),
        // Manual TOC entries
        new Table({
          columnWidths: [7800, 1560],
          rows: [
            // Executive Summary
            new TableRow({
              children: [
                new TableCell({
                  borders: noBorders,
                  width: { size: 7800, type: WidthType.DXA },
                  children: [new Paragraph({
                    spacing: { before: 200, after: 200 },
                    children: [new TextRun({ text: "Executive Summary", bold: true, size: 28, color: DARK_BLUE, font: "Arial" })]
                  })]
                }),
                new TableCell({
                  borders: noBorders,
                  width: { size: 1560, type: WidthType.DXA },
                  children: [new Paragraph({
                    alignment: AlignmentType.RIGHT,
                    spacing: { before: 200, after: 200 },
                    children: [new TextRun({ text: "03", bold: true, size: 28, color: ACCENT_BLUE, font: "Arial" })]
                  })]
                })
              ]
            }),
            // Chapter 1
            new TableRow({
              children: [
                new TableCell({
                  borders: noBorders,
                  shading: { fill: LIGHT_GRAY, type: ShadingType.CLEAR },
                  width: { size: 7800, type: WidthType.DXA },
                  children: [new Paragraph({
                    spacing: { before: 200, after: 200 },
                    children: [new TextRun({ text: "Chapter 1: The AI Landscape in 2026", bold: true, size: 28, color: DARK_BLUE, font: "Arial" })]
                  })]
                }),
                new TableCell({
                  borders: noBorders,
                  shading: { fill: LIGHT_GRAY, type: ShadingType.CLEAR },
                  width: { size: 1560, type: WidthType.DXA },
                  children: [new Paragraph({
                    alignment: AlignmentType.RIGHT,
                    spacing: { before: 200, after: 200 },
                    children: [new TextRun({ text: "04", bold: true, size: 28, color: ACCENT_BLUE, font: "Arial" })]
                  })]
                })
              ]
            }),
            // Sub items for Chapter 1
            new TableRow({
              children: [
                new TableCell({
                  borders: noBorders,
                  width: { size: 7800, type: WidthType.DXA },
                  children: [new Paragraph({
                    spacing: { before: 100, after: 100 },
                    indent: { left: 400 },
                    children: [new TextRun({ text: "The Rise of Reasoning Models", size: 24, color: GRAY, font: "Arial" })]
                  })]
                }),
                new TableCell({
                  borders: noBorders,
                  width: { size: 1560, type: WidthType.DXA },
                  children: [new Paragraph({ children: [] })]
                })
              ]
            }),
            new TableRow({
              children: [
                new TableCell({
                  borders: noBorders,
                  width: { size: 7800, type: WidthType.DXA },
                  children: [new Paragraph({
                    spacing: { before: 100, after: 100 },
                    indent: { left: 400 },
                    children: [new TextRun({ text: "Agent-Based Architectures", size: 24, color: GRAY, font: "Arial" })]
                  })]
                }),
                new TableCell({
                  borders: noBorders,
                  width: { size: 1560, type: WidthType.DXA },
                  children: [new Paragraph({ children: [] })]
                })
              ]
            }),
            new TableRow({
              children: [
                new TableCell({
                  borders: noBorders,
                  width: { size: 7800, type: WidthType.DXA },
                  children: [new Paragraph({
                    spacing: { before: 100, after: 100 },
                    indent: { left: 400 },
                    children: [new TextRun({ text: "The MCP Revolution", size: 24, color: GRAY, font: "Arial" })]
                  })]
                }),
                new TableCell({
                  borders: noBorders,
                  width: { size: 1560, type: WidthType.DXA },
                  children: [new Paragraph({ children: [] })]
                })
              ]
            }),
            // Chapter 2
            new TableRow({
              children: [
                new TableCell({
                  borders: noBorders,
                  shading: { fill: LIGHT_GRAY, type: ShadingType.CLEAR },
                  width: { size: 7800, type: WidthType.DXA },
                  children: [new Paragraph({
                    spacing: { before: 200, after: 200 },
                    children: [new TextRun({ text: "Chapter 2: Implementation Strategies That Work", bold: true, size: 28, color: DARK_BLUE, font: "Arial" })]
                  })]
                }),
                new TableCell({
                  borders: noBorders,
                  shading: { fill: LIGHT_GRAY, type: ShadingType.CLEAR },
                  width: { size: 1560, type: WidthType.DXA },
                  children: [new Paragraph({
                    alignment: AlignmentType.RIGHT,
                    spacing: { before: 200, after: 200 },
                    children: [new TextRun({ text: "05", bold: true, size: 28, color: ACCENT_BLUE, font: "Arial" })]
                  })]
                })
              ]
            }),
            // Sub items for Chapter 2
            new TableRow({
              children: [
                new TableCell({
                  borders: noBorders,
                  width: { size: 7800, type: WidthType.DXA },
                  children: [new Paragraph({
                    spacing: { before: 100, after: 100 },
                    indent: { left: 400 },
                    children: [new TextRun({ text: "The Three-Horizon Framework", size: 24, color: GRAY, font: "Arial" })]
                  })]
                }),
                new TableCell({
                  borders: noBorders,
                  width: { size: 1560, type: WidthType.DXA },
                  children: [new Paragraph({ children: [] })]
                })
              ]
            }),
            new TableRow({
              children: [
                new TableCell({
                  borders: noBorders,
                  width: { size: 7800, type: WidthType.DXA },
                  children: [new Paragraph({
                    spacing: { before: 100, after: 100 },
                    indent: { left: 400 },
                    children: [new TextRun({ text: "Critical Success Factors", size: 24, color: GRAY, font: "Arial" })]
                  })]
                }),
                new TableCell({
                  borders: noBorders,
                  width: { size: 1560, type: WidthType.DXA },
                  children: [new Paragraph({ children: [] })]
                })
              ]
            }),
            // Chapter 3
            new TableRow({
              children: [
                new TableCell({
                  borders: noBorders,
                  shading: { fill: LIGHT_GRAY, type: ShadingType.CLEAR },
                  width: { size: 7800, type: WidthType.DXA },
                  children: [new Paragraph({
                    spacing: { before: 200, after: 200 },
                    children: [new TextRun({ text: "Chapter 3: Industry-Specific Applications", bold: true, size: 28, color: DARK_BLUE, font: "Arial" })]
                  })]
                }),
                new TableCell({
                  borders: noBorders,
                  shading: { fill: LIGHT_GRAY, type: ShadingType.CLEAR },
                  width: { size: 1560, type: WidthType.DXA },
                  children: [new Paragraph({
                    alignment: AlignmentType.RIGHT,
                    spacing: { before: 200, after: 200 },
                    children: [new TextRun({ text: "06", bold: true, size: 28, color: ACCENT_BLUE, font: "Arial" })]
                  })]
                })
              ]
            }),
            // Chapter 4
            new TableRow({
              children: [
                new TableCell({
                  borders: noBorders,
                  width: { size: 7800, type: WidthType.DXA },
                  children: [new Paragraph({
                    spacing: { before: 200, after: 200 },
                    children: [new TextRun({ text: "Chapter 4: Building Your AI-Ready Organization", bold: true, size: 28, color: DARK_BLUE, font: "Arial" })]
                  })]
                }),
                new TableCell({
                  borders: noBorders,
                  width: { size: 1560, type: WidthType.DXA },
                  children: [new Paragraph({
                    alignment: AlignmentType.RIGHT,
                    spacing: { before: 200, after: 200 },
                    children: [new TextRun({ text: "07", bold: true, size: 28, color: ACCENT_BLUE, font: "Arial" })]
                  })]
                })
              ]
            }),
            // Chapter 5
            new TableRow({
              children: [
                new TableCell({
                  borders: noBorders,
                  shading: { fill: LIGHT_GRAY, type: ShadingType.CLEAR },
                  width: { size: 7800, type: WidthType.DXA },
                  children: [new Paragraph({
                    spacing: { before: 200, after: 200 },
                    children: [new TextRun({ text: "Chapter 5: What's Next—2027 and Beyond", bold: true, size: 28, color: DARK_BLUE, font: "Arial" })]
                  })]
                }),
                new TableCell({
                  borders: noBorders,
                  shading: { fill: LIGHT_GRAY, type: ShadingType.CLEAR },
                  width: { size: 1560, type: WidthType.DXA },
                  children: [new Paragraph({
                    alignment: AlignmentType.RIGHT,
                    spacing: { before: 200, after: 200 },
                    children: [new TextRun({ text: "08", bold: true, size: 28, color: ACCENT_BLUE, font: "Arial" })]
                  })]
                })
              ]
            }),
            // Conclusion
            new TableRow({
              children: [
                new TableCell({
                  borders: noBorders,
                  width: { size: 7800, type: WidthType.DXA },
                  children: [new Paragraph({
                    spacing: { before: 200, after: 200 },
                    children: [new TextRun({ text: "Conclusion: The Time for Action is Now", bold: true, size: 28, color: DARK_BLUE, font: "Arial" })]
                  })]
                }),
                new TableCell({
                  borders: noBorders,
                  width: { size: 1560, type: WidthType.DXA },
                  children: [new Paragraph({
                    alignment: AlignmentType.RIGHT,
                    spacing: { before: 200, after: 200 },
                    children: [new TextRun({ text: "09", bold: true, size: 28, color: ACCENT_BLUE, font: "Arial" })]
                  })]
                })
              ]
            }),
            // About
            new TableRow({
              children: [
                new TableCell({
                  borders: noBorders,
                  shading: { fill: LIGHT_GRAY, type: ShadingType.CLEAR },
                  width: { size: 7800, type: WidthType.DXA },
                  children: [new Paragraph({
                    spacing: { before: 200, after: 200 },
                    children: [new TextRun({ text: "About Prompt Advisers", bold: true, size: 28, color: DARK_BLUE, font: "Arial" })]
                  })]
                }),
                new TableCell({
                  borders: noBorders,
                  shading: { fill: LIGHT_GRAY, type: ShadingType.CLEAR },
                  width: { size: 1560, type: WidthType.DXA },
                  children: [new Paragraph({
                    alignment: AlignmentType.RIGHT,
                    spacing: { before: 200, after: 200 },
                    children: [new TextRun({ text: "10", bold: true, size: 28, color: ACCENT_BLUE, font: "Arial" })]
                  })]
                })
              ]
            })
          ]
        })
      ]
    },
    // ============ MAIN CONTENT SECTION ============
    {
      properties: {
        page: { margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } }
      },
      headers: {
        default: new Header({
          children: [
            new Table({
              columnWidths: [9360],
              rows: [
                new TableRow({
                  children: [
                    new TableCell({
                      borders: { top: noBorder, bottom: { style: BorderStyle.SINGLE, size: 12, color: ACCENT_BLUE }, left: noBorder, right: noBorder },
                      width: { size: 9360, type: WidthType.DXA },
                      children: [
                        new Table({
                          columnWidths: [4680, 4680],
                          rows: [
                            new TableRow({
                              children: [
                                new TableCell({
                                  borders: noBorders,
                                  width: { size: 4680, type: WidthType.DXA },
                                  children: [new Paragraph({
                                    children: [new TextRun({ text: "THE STATE OF AI 2026", bold: true, size: 18, color: DARK_BLUE, font: "Arial" })]
                                  })]
                                }),
                                new TableCell({
                                  borders: noBorders,
                                  width: { size: 4680, type: WidthType.DXA },
                                  children: [new Paragraph({
                                    alignment: AlignmentType.RIGHT,
                                    children: [new TextRun({ text: "PROMPT ADVISERS", bold: true, size: 18, color: ACCENT_BLUE, font: "Arial" })]
                                  })]
                                })
                              ]
                            })
                          ]
                        })
                      ]
                    })
                  ]
                })
              ]
            })
          ]
        })
      },
      footers: {
        default: new Footer({
          children: [
            new Paragraph({
              alignment: AlignmentType.CENTER,
              children: [
                new TextRun({ text: "— ", size: 20, color: ACCENT_BLUE, font: "Arial" }),
                new TextRun({ children: [PageNumber.CURRENT], bold: true, size: 20, color: DARK_BLUE, font: "Arial" }),
                new TextRun({ text: " —", size: 20, color: ACCENT_BLUE, font: "Arial" })
              ]
            })
          ]
        })
      },
      children: [
        // EXECUTIVE SUMMARY with colored header
        createSectionHeader("Executive Summary"),
        new Paragraph({ spacing: { before: 300 }, children: [] }),
        new Paragraph({
          spacing: { after: 200 },
          children: [new TextRun({ text: "2026 marks a pivotal inflection point in enterprise AI adoption. What was once experimental has become essential. Organizations that delay implementation now risk irreversible competitive disadvantage, while those who move strategically are capturing outsized returns.", size: 24, font: "Arial" })]
        }),
        createPullQuote(
          "The window for AI competitive advantage is closing. By 2027, AI capabilities will be table stakes, not differentiators.",
          "McKinsey Global Institute, 2025"
        ),
        new Paragraph({
          spacing: { before: 300, after: 200 },
          children: [new TextRun({ text: "This report synthesizes findings from over 500 enterprise AI implementations, interviews with 50 C-suite executives, and analysis of the latest technological developments to provide a practical roadmap for business leaders navigating this transformation.", size: 24, font: "Arial" })]
        }),
        // Bold stats row with colored backgrounds
        new Paragraph({ spacing: { before: 300 }, children: [] }),
        new Table({
          columnWidths: [3120, 3120, 3120],
          rows: [
            new TableRow({
              children: [
                new TableCell({
                  borders: noBorders,
                  width: { size: 3120, type: WidthType.DXA },
                  children: [createStatBox("78%", "enterprises deploying production AI by 2026", DARK_BLUE)]
                }),
                new TableCell({
                  borders: noBorders,
                  width: { size: 3120, type: WidthType.DXA },
                  children: [createStatBox("$4.4T", "projected global AI market value", ACCENT_BLUE)]
                }),
                new TableCell({
                  borders: noBorders,
                  width: { size: 3120, type: WidthType.DXA },
                  children: [createStatBox("23%", "average productivity gain from AI", DARK_BLUE)]
                })
              ]
            })
          ]
        }),
        new Paragraph({ children: [new PageBreak()] }),

        // CHAPTER 1
        createSectionHeader("Chapter 1: The AI Landscape in 2026"),
        new Paragraph({ spacing: { before: 300 }, children: [] }),
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun("Key Technological Shifts")]
        }),
        new Paragraph({
          spacing: { after: 200 },
          children: [new TextRun({ text: "The AI ecosystem has undergone dramatic transformation since 2024. Several foundational shifts have reshaped what's possible and practical for enterprises:", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          heading: HeadingLevel.HEADING_3,
          children: [new TextRun("1. The Rise of Reasoning Models")]
        }),
        new Paragraph({
          spacing: { after: 200 },
          children: [new TextRun({ text: "Claude, GPT, and Gemini have evolved from pattern-matching systems to genuine reasoning engines. The introduction of extended thinking capabilities means these models can now tackle multi-step problems that previously required human expertise.", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          numbering: { reference: "bullet-list", level: 0 },
          children: [new TextRun({ text: "Complex analysis tasks that took teams days now complete in minutes", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          numbering: { reference: "bullet-list", level: 0 },
          children: [new TextRun({ text: "Error rates have dropped below human baseline for many cognitive tasks", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          numbering: { reference: "bullet-list", level: 0 },
          children: [new TextRun({ text: "Chain-of-thought transparency enables audit and compliance", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          heading: HeadingLevel.HEADING_3,
          children: [new TextRun("2. Agent-Based Architectures")]
        }),
        new Paragraph({
          spacing: { after: 200 },
          children: [new TextRun({ text: "2026 is the year AI agents graduate from demos to deployment. Multi-agent systems now coordinate complex workflows across enterprise functions, from procurement to customer service to financial operations.", size: 24, font: "Arial" })]
        }),
        createPullQuote(
          "We're not building AI assistants anymore. We're building AI employees that happen to run on silicon instead of coffee.",
          "CTO, Fortune 500 Retailer"
        ),
        new Paragraph({
          heading: HeadingLevel.HEADING_3,
          children: [new TextRun("3. The MCP Revolution")]
        }),
        new Paragraph({
          spacing: { after: 200 },
          children: [new TextRun({ text: "The Model Context Protocol (MCP) has emerged as the USB standard of AI integration. Enterprises can now connect AI systems to their existing infrastructure through standardized interfaces, dramatically reducing implementation timelines from months to weeks.", size: 24, font: "Arial" })]
        }),
        new Paragraph({ children: [new PageBreak()] }),

        // CHAPTER 2
        createSectionHeader("Chapter 2: Implementation Strategies That Work"),
        new Paragraph({ spacing: { before: 300 }, children: [] }),
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun("The Three-Horizon Framework")]
        }),
        new Paragraph({
          spacing: { after: 200 },
          children: [new TextRun({ text: "Based on our analysis of successful enterprise implementations, we've identified a consistent pattern among organizations achieving above-average ROI on AI investments:", size: 24, font: "Arial" })]
        }),
        // Bold framework table
        new Table({
          columnWidths: [2340, 3510, 3510],
          rows: [
            new TableRow({
              tableHeader: true,
              children: [
                new TableCell({
                  borders: noBorders,
                  shading: { fill: DARK_BLUE, type: ShadingType.CLEAR },
                  width: { size: 2340, type: WidthType.DXA },
                  children: [new Paragraph({
                    spacing: { before: 150, after: 150 },
                    children: [new TextRun({ text: "HORIZON", bold: true, size: 22, color: WHITE, font: "Arial" })]
                  })]
                }),
                new TableCell({
                  borders: noBorders,
                  shading: { fill: DARK_BLUE, type: ShadingType.CLEAR },
                  width: { size: 3510, type: WidthType.DXA },
                  children: [new Paragraph({
                    spacing: { before: 150, after: 150 },
                    children: [new TextRun({ text: "FOCUS", bold: true, size: 22, color: WHITE, font: "Arial" })]
                  })]
                }),
                new TableCell({
                  borders: noBorders,
                  shading: { fill: DARK_BLUE, type: ShadingType.CLEAR },
                  width: { size: 3510, type: WidthType.DXA },
                  children: [new Paragraph({
                    spacing: { before: 150, after: 150 },
                    children: [new TextRun({ text: "EXPECTED ROI", bold: true, size: 22, color: WHITE, font: "Arial" })]
                  })]
                })
              ]
            }),
            new TableRow({
              children: [
                new TableCell({
                  borders: noBorders,
                  shading: { fill: LIGHT_BLUE, type: ShadingType.CLEAR },
                  width: { size: 2340, type: WidthType.DXA },
                  children: [new Paragraph({
                    spacing: { before: 150, after: 150 },
                    children: [new TextRun({ text: "H1: Quick Wins", bold: true, size: 22, color: DARK_BLUE, font: "Arial" })]
                  })]
                }),
                new TableCell({
                  borders: noBorders,
                  shading: { fill: LIGHT_BLUE, type: ShadingType.CLEAR },
                  width: { size: 3510, type: WidthType.DXA },
                  children: [new Paragraph({
                    spacing: { before: 150, after: 150 },
                    children: [new TextRun({ text: "Productivity tools, document automation, customer service chatbots", size: 22, font: "Arial" })]
                  })]
                }),
                new TableCell({
                  borders: noBorders,
                  shading: { fill: LIGHT_BLUE, type: ShadingType.CLEAR },
                  width: { size: 3510, type: WidthType.DXA },
                  children: [new Paragraph({
                    spacing: { before: 150, after: 150 },
                    children: [new TextRun({ text: "15-30% efficiency gains within 90 days", bold: true, size: 22, color: ACCENT_BLUE, font: "Arial" })]
                  })]
                })
              ]
            }),
            new TableRow({
              children: [
                new TableCell({
                  borders: noBorders,
                  shading: { fill: WHITE, type: ShadingType.CLEAR },
                  width: { size: 2340, type: WidthType.DXA },
                  children: [new Paragraph({
                    spacing: { before: 150, after: 150 },
                    children: [new TextRun({ text: "H2: Process Transformation", bold: true, size: 22, color: DARK_BLUE, font: "Arial" })]
                  })]
                }),
                new TableCell({
                  borders: noBorders,
                  shading: { fill: WHITE, type: ShadingType.CLEAR },
                  width: { size: 3510, type: WidthType.DXA },
                  children: [new Paragraph({
                    spacing: { before: 150, after: 150 },
                    children: [new TextRun({ text: "Workflow automation, agent deployment, integrated AI operations", size: 22, font: "Arial" })]
                  })]
                }),
                new TableCell({
                  borders: noBorders,
                  shading: { fill: WHITE, type: ShadingType.CLEAR },
                  width: { size: 3510, type: WidthType.DXA },
                  children: [new Paragraph({
                    spacing: { before: 150, after: 150 },
                    children: [new TextRun({ text: "40-60% cost reduction in target processes", bold: true, size: 22, color: ACCENT_BLUE, font: "Arial" })]
                  })]
                })
              ]
            }),
            new TableRow({
              children: [
                new TableCell({
                  borders: noBorders,
                  shading: { fill: LIGHT_BLUE, type: ShadingType.CLEAR },
                  width: { size: 2340, type: WidthType.DXA },
                  children: [new Paragraph({
                    spacing: { before: 150, after: 150 },
                    children: [new TextRun({ text: "H3: Business Model Innovation", bold: true, size: 22, color: DARK_BLUE, font: "Arial" })]
                  })]
                }),
                new TableCell({
                  borders: noBorders,
                  shading: { fill: LIGHT_BLUE, type: ShadingType.CLEAR },
                  width: { size: 3510, type: WidthType.DXA },
                  children: [new Paragraph({
                    spacing: { before: 150, after: 150 },
                    children: [new TextRun({ text: "AI-native products, new revenue streams, market expansion", size: 22, font: "Arial" })]
                  })]
                }),
                new TableCell({
                  borders: noBorders,
                  shading: { fill: LIGHT_BLUE, type: ShadingType.CLEAR },
                  width: { size: 3510, type: WidthType.DXA },
                  children: [new Paragraph({
                    spacing: { before: 150, after: 150 },
                    children: [new TextRun({ text: "10-100x returns through new market capture", bold: true, size: 22, color: ACCENT_BLUE, font: "Arial" })]
                  })]
                })
              ]
            })
          ]
        }),
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun("Critical Success Factors")]
        }),
        new Paragraph({
          spacing: { after: 150 },
          children: [new TextRun({ text: "Our research identified five factors that consistently separated successful AI implementations from failed initiatives:", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          numbering: { reference: "numbered-list-1", level: 0 },
          spacing: { after: 100 },
          children: [new TextRun({ text: "Executive sponsorship with genuine understanding of AI capabilities and limitations", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          numbering: { reference: "numbered-list-1", level: 0 },
          spacing: { after: 100 },
          children: [new TextRun({ text: "Clear success metrics defined before implementation begins", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          numbering: { reference: "numbered-list-1", level: 0 },
          spacing: { after: 100 },
          children: [new TextRun({ text: "Cross-functional implementation teams with both technical and domain expertise", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          numbering: { reference: "numbered-list-1", level: 0 },
          spacing: { after: 100 },
          children: [new TextRun({ text: "Iterative deployment with continuous feedback loops", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          numbering: { reference: "numbered-list-1", level: 0 },
          spacing: { after: 100 },
          children: [new TextRun({ text: "Change management investment proportional to technical investment", size: 24, font: "Arial" })]
        }),
        new Paragraph({ children: [new PageBreak()] }),

        // CHAPTER 3
        createSectionHeader("Chapter 3: Industry-Specific Applications"),
        new Paragraph({ spacing: { before: 300 }, children: [] }),
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun("Financial Services")]
        }),
        new Paragraph({
          spacing: { after: 200 },
          children: [new TextRun({ text: "The financial sector leads AI adoption with 84% of institutions now running production AI workloads. Key applications include:", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          numbering: { reference: "bullet-list", level: 0 },
          children: [new TextRun({ text: "Real-time fraud detection with 99.7% accuracy rates", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          numbering: { reference: "bullet-list", level: 0 },
          children: [new TextRun({ text: "Automated regulatory compliance monitoring and reporting", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          numbering: { reference: "bullet-list", level: 0 },
          children: [new TextRun({ text: "AI-powered wealth management and personalized portfolio optimization", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          numbering: { reference: "bullet-list", level: 0 },
          children: [new TextRun({ text: "Intelligent document processing reducing loan processing time by 70%", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun("Healthcare")]
        }),
        new Paragraph({
          spacing: { after: 200 },
          children: [new TextRun({ text: "Healthcare AI has moved from experimental to essential, with regulatory frameworks now mature enough to enable widespread deployment:", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          numbering: { reference: "bullet-list", level: 0 },
          children: [new TextRun({ text: "Diagnostic assistance achieving specialist-level accuracy in radiology and pathology", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          numbering: { reference: "bullet-list", level: 0 },
          children: [new TextRun({ text: "Clinical documentation automation saving physicians 2+ hours daily", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          numbering: { reference: "bullet-list", level: 0 },
          children: [new TextRun({ text: "Drug discovery pipelines accelerated by 40% through AI-powered molecular modeling", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun("Manufacturing")]
        }),
        new Paragraph({
          spacing: { after: 200 },
          children: [new TextRun({ text: "Smart manufacturing has reached maturity with AI systems now managing entire production lines:", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          numbering: { reference: "bullet-list", level: 0 },
          children: [new TextRun({ text: "Predictive maintenance reducing unplanned downtime by 45%", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          numbering: { reference: "bullet-list", level: 0 },
          children: [new TextRun({ text: "Quality control automation achieving defect detection rates exceeding 99.9%", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          numbering: { reference: "bullet-list", level: 0 },
          children: [new TextRun({ text: "Supply chain optimization reducing inventory costs by 20-30%", size: 24, font: "Arial" })]
        }),
        new Paragraph({ children: [new PageBreak()] }),

        // CHAPTER 4
        createSectionHeader("Chapter 4: Building Your AI-Ready Organization"),
        new Paragraph({ spacing: { before: 300 }, children: [] }),
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun("The Skills Gap Reality")]
        }),
        new Paragraph({
          spacing: { after: 200 },
          children: [new TextRun({ text: "The most significant barrier to AI adoption isn't technology—it's talent. Our survey found that 67% of enterprises cite skills gaps as their primary implementation challenge.", size: 24, font: "Arial" })]
        }),
        createPullQuote(
          "The organizations winning at AI aren't necessarily the ones with the biggest budgets. They're the ones who invested early in their people.",
          "VP of Digital Transformation, Global Manufacturer"
        ),
        new Paragraph({
          heading: HeadingLevel.HEADING_3,
          children: [new TextRun("Essential Competencies for 2026")]
        }),
        new Paragraph({
          spacing: { after: 150 },
          children: [new TextRun({ text: "Beyond technical skills, successful AI teams require:", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          numbering: { reference: "numbered-list-2", level: 0 },
          spacing: { after: 100 },
          children: [
            new TextRun({ text: "Prompt Engineering Excellence: ", bold: true, size: 24, font: "Arial", color: ACCENT_BLUE }),
            new TextRun({ text: "The ability to effectively communicate with AI systems is now as fundamental as coding.", size: 24, font: "Arial" })
          ]
        }),
        new Paragraph({
          numbering: { reference: "numbered-list-2", level: 0 },
          spacing: { after: 100 },
          children: [
            new TextRun({ text: "Systems Thinking: ", bold: true, size: 24, font: "Arial", color: ACCENT_BLUE }),
            new TextRun({ text: "Understanding how AI components integrate into broader business processes.", size: 24, font: "Arial" })
          ]
        }),
        new Paragraph({
          numbering: { reference: "numbered-list-2", level: 0 },
          spacing: { after: 100 },
          children: [
            new TextRun({ text: "Ethical Reasoning: ", bold: true, size: 24, font: "Arial", color: ACCENT_BLUE }),
            new TextRun({ text: "Navigating the complex governance landscape around AI deployment.", size: 24, font: "Arial" })
          ]
        }),
        new Paragraph({
          numbering: { reference: "numbered-list-2", level: 0 },
          spacing: { after: 100 },
          children: [
            new TextRun({ text: "Change Leadership: ", bold: true, size: 24, font: "Arial", color: ACCENT_BLUE }),
            new TextRun({ text: "Guiding organizations through AI-driven transformation.", size: 24, font: "Arial" })
          ]
        }),
        new Paragraph({ children: [new PageBreak()] }),

        // CHAPTER 5
        createSectionHeader("Chapter 5: What's Next—2027 and Beyond"),
        new Paragraph({ spacing: { before: 300 }, children: [] }),
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun("Emerging Technologies to Watch")]
        }),
        new Paragraph({
          spacing: { after: 200 },
          children: [new TextRun({ text: "While 2026 is about executing on proven approaches, forward-thinking organizations are already positioning for the next wave:", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          heading: HeadingLevel.HEADING_3,
          children: [new TextRun("Autonomous Agent Networks")]
        }),
        new Paragraph({
          spacing: { after: 200 },
          children: [new TextRun({ text: "Multi-agent systems that can autonomously negotiate, transact, and collaborate are moving from research to early production. Expect significant commercial deployments by late 2027.", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          heading: HeadingLevel.HEADING_3,
          children: [new TextRun("AI-Native Development")]
        }),
        new Paragraph({
          spacing: { after: 200 },
          children: [new TextRun({ text: "Software development is being fundamentally reimagined. AI coding assistants have evolved into AI developers capable of building complete applications. This shift will reshape the economics of software creation.", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          heading: HeadingLevel.HEADING_3,
          children: [new TextRun("Personalized Intelligence")]
        }),
        new Paragraph({
          spacing: { after: 200 },
          children: [new TextRun({ text: "AI systems that learn and adapt to individual users are enabling unprecedented levels of customization. From personalized education to adaptive healthcare, the one-size-fits-all era is ending.", size: 24, font: "Arial" })]
        }),
        new Paragraph({ children: [new PageBreak()] }),

        // CONCLUSION
        createSectionHeader("Conclusion: The Time for Action is Now"),
        new Paragraph({ spacing: { before: 300 }, children: [] }),
        new Paragraph({
          spacing: { after: 200 },
          children: [new TextRun({ text: "The state of AI in 2026 is one of unprecedented opportunity tempered by real implementation challenges. The technology has matured beyond the hype cycle—we now have proven playbooks for enterprise deployment.", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          spacing: { after: 200 },
          children: [new TextRun({ text: "The organizations that will thrive are those taking decisive action today. Not reckless experimentation, but strategic, well-governed implementation guided by clear business objectives.", size: 24, font: "Arial" })]
        }),
        createPullQuote(
          "In five years, every company will be an AI company. The only question is whether you'll be leading or following.",
          "Mark Kashef, Founder & CEO, Prompt Advisers"
        ),
        new Paragraph({
          spacing: { before: 300, after: 200 },
          children: [new TextRun({ text: "The path forward is clear. The tools are ready. The only variable is your commitment to transformation.", size: 24, font: "Arial", bold: true })]
        }),
        new Paragraph({ children: [new PageBreak()] }),

        // ABOUT SECTION
        createSectionHeader("About Prompt Advisers"),
        new Paragraph({ spacing: { before: 300 }, children: [] }),
        new Paragraph({
          spacing: { after: 200 },
          children: [new TextRun({ text: "Prompt Advisers is a seven-figure AI consulting agency specializing in AI strategy, automation, and implementation for enterprise clients. Founded by Mark Kashef, a Queen's University AI graduate with over 10 years of experience including leadership roles at Amazon, Prompt Advisers has helped hundreds of organizations successfully navigate their AI transformation journey.", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun("Our Services")]
        }),
        new Paragraph({
          numbering: { reference: "bullet-list", level: 0 },
          children: [new TextRun({ text: "AI Strategy Development and Roadmapping", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          numbering: { reference: "bullet-list", level: 0 },
          children: [new TextRun({ text: "Enterprise AI Implementation", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          numbering: { reference: "bullet-list", level: 0 },
          children: [new TextRun({ text: "AI Agent Development and Deployment", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          numbering: { reference: "bullet-list", level: 0 },
          children: [new TextRun({ text: "Team Training and Capability Building", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          numbering: { reference: "bullet-list", level: 0 },
          children: [new TextRun({ text: "AI Governance Framework Design", size: 24, font: "Arial" })]
        }),
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun("Connect With Us")]
        }),
        new Paragraph({
          spacing: { after: 100 },
          children: [
            new TextRun({ text: "Website: ", bold: true, size: 24, font: "Arial" }),
            new TextRun({ text: "promptadvisers.com", size: 24, font: "Arial", color: ACCENT_BLUE })
          ]
        }),
        new Paragraph({
          spacing: { after: 100 },
          children: [
            new TextRun({ text: "YouTube: ", bold: true, size: 24, font: "Arial" }),
            new TextRun({ text: "55,000+ subscribers learning practical AI implementation", size: 24, font: "Arial" })
          ]
        }),
        new Paragraph({
          spacing: { after: 100 },
          children: [
            new TextRun({ text: "Community: ", bold: true, size: 24, font: "Arial" }),
            new TextRun({ text: "Early AI-dopters (700+ members)", size: 24, font: "Arial" })
          ]
        })
      ]
    }
  ]
});

Packer.toBuffer(doc).then(buffer => {
  const outputPath = path.join(rootDir, 'output', 'State_of_AI_2026.docx');
  fs.writeFileSync(outputPath, buffer);
  console.log(`Report created successfully: ${outputPath}`);
});
